name: Clang Format Check

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install clang-format
    - name: Run clang-format-check
      run: sh external/misc/clang-format-check.sh